# Generated by Django 5.1.3 on 2024-11-15 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogging", "0002_category_more_details"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.RemoveField(
            model_name="category",
            name="more_details",
        ),
    ]
